auto_parts_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls", namespace="shop")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from shop.views import (
    index,
    LogoutView,
    SignUpView,
    ManufacturerListView,
    AutopartListView,
    add_item_to_order,
    remove_part_from_order,
    basket,
    CustomerDetailView,
    CustomerUpdateView,
    manufacturer_detail_parts,
)

urlpatterns = [
    path("", index, name="index"),
    path("login/home/", index, name="index"),
    path(
        "login/",
        LoginView.as_view(
            template_name='registration/login.html',
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("register/", SignUpView.as_view(), name="register"),
    path(
        "manufacturers/",
        ManufacturerListView.as_view(),
        name="manufacturer-list",
    ),
    path(
        "auto-parts/",
        AutopartListView.as_view(),
        name="autopart-list",
    ),
    path("auto-parts/<int:pk>/buy/", add_item_to_order, name="buy"),
    path("basket/", basket, name="basket"),
    path(
        "customer/<int:pk>/",
        CustomerDetailView.as_view(),
        name="customer-detail"
    ),
    path(
        "customer/<int:pk>/update",
        CustomerUpdateView.as_view(),
        name="customer-update"
    ),
    path(
        "basket/<int:pk>/remove/",
        remove_part_from_order,
        name="remove"
    ),
    path(
        "manufacturer/<int:pk>/",
        manufacturer_detail_parts,
        name="manufacturer-detail"
    )
]

app_name = "shop"

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
    <nav aria-label="pagination">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link"><<<</a>
          </li>
        {% endif %}
        <li class="page-item active">
          <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
        </li>
        {% if page_obj.has_next %}
          <li class="page-item float-sm-right">
            <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">>>></a>
          </li>
        {% endif %}
      </ul>
    </nav>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group sidebar">
  {% if user.is_authenticated %}
    <li
       class="list-group-item sidebar">User: <a class="link_color" href="{{ user.get_absolute_url }}">{{ user.get_username }}</a>
       {% if user.is_staff %} Is staff{% endif %}
    </li>
    <li class="list-group-item sidebar"><a class="link_color" href="{% url 'shop:logout'%}?next={{request.path}}">Logout</a></li>
    <li class="list-group-item sidebar"><a class="link_color" href="{% url 'shop:basket'%}?next={{request.path}}">Basket</a></li>
  {% else %}
    <li class="list-group-item sidebar"><a class="link_color" href="{% url 'shop:login'%}?next={{request.path}}">Sing In</a></li>
    <li class="list-group-item sidebar"><a class="link_color" href="{% url 'shop:register'%}?next={{request.path}}">Sing Up</a></li>
  {% endif %}

  <li class="list-group-item sidebar"><a class="link_color" href="{% url 'shop:index' %}">Home</a></li>
  <li class="list-group-item sidebar"><a class="link_color" href="{% url 'shop:manufacturer-list' %}">All manufacturers</a></li>
  <li class="list-group-item sidebar"><a class="link_color" href="{% url 'shop:autopart-list' %}">All auto-parts</a></li>
</ul>