auto_parts_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls", namespace="shop")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from shop.views import (
    index,
    LogoutView,
    SignUpView,
    ManufacturerListView,
    AutopartListView,
    add_item_to_order,
    remove_part_from_order,
    basket,
    CustomerDetailView,
    CustomerUpdateView,
    manufacturer_detail_parts,
)

urlpatterns = [
    path("", index, name="index"),
    path("login/home/", index, name="index"),
    path(
        "login/",
        LoginView.as_view(
            template_name='registration/login.html',
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("register/", SignUpView.as_view(), name="register"),
    path(
        "manufacturers/",
        ManufacturerListView.as_view(),
        name="manufacturer-list",
    ),
    path(
        "auto-parts/",
        AutopartListView.as_view(),
        name="autopart-list",
    ),
    path("auto-parts/<int:pk>/buy/", add_item_to_order, name="buy"),
    path("basket/", basket, name="basket"),
    path(
        "customer/<int:pk>/",
        CustomerDetailView.as_view(),
        name="customer-detail"
    ),
    path(
        "customer/<int:pk>/update",
        CustomerUpdateView.as_view(),
        name="customer-update"
    ),
    path(
        "basket/<int:pk>/remove/",
        remove_part_from_order,
        name="remove"
    ),
    path(
        "manufacturer/<int:pk>/",
        manufacturer_detail_parts,
        name="manufacturer-detail"
    )
]

app_name = "shop"

shop/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.country}"


class AutoPart(models.Model):
    part_name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    manufacturer = models.ForeignKey(
        to=Manufacturer,
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name_plural = "auto_parts"

    def __str__(self):
        return f"{self.part_name}, price: ({self.price})"


class Customer(AbstractUser):

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("shop:customer-detail", kwargs={"pk": self.pk})


class Order(models.Model):
    auto_parts = models.ManyToManyField(to=AutoPart)
    owner = models.ForeignKey(to=Customer, on_delete=models.CASCADE)

    def __str__(self):
        return f"Order number: {self.id}"

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from shop.models import Customer


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = Customer
        fields = ("username", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class ManufacturerSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name..."
            }
        )
    )


class AutopartsSearchForm(forms.Form):
    part_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name..."
            }
        )
    )

shop/views.py
import sweetify
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View, generic
from sweetify.views import SweetifySuccessMixin

from shop.forms import NewUserForm, ManufacturerSearchForm, AutopartsSearchForm
from shop.models import Manufacturer, AutoPart, Customer, Order


def index(request):
    """View function for the home page of the site."""
    manufacturer_count = Manufacturer.objects.all().count()
    autoparts_count = AutoPart.objects.all().count()
    users_count = Customer.objects.all().count()

    context = {
        "manufacturer_count": manufacturer_count,
        "autoparts_count": autoparts_count,
        "users_count": users_count,
    }
    return render(request, "shop/index.html", context=context)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return render(request, "registration/logged_out.html")


class SignUpView(SweetifySuccessMixin, generic.CreateView):
    template_name = "registration/register.html"
    success_url = reverse_lazy('shop:login')
    form_class = NewUserForm
    success_message = "Your profile was created successfully"


class CustomerDetailView(generic.DetailView):
    model = Customer


class CustomerUpdateView(SweetifySuccessMixin, generic.UpdateView):
    model = Customer
    fields = ["username", "first_name", "last_name", "email"]
    success_message = "Your profile was updated successfully"

    def get_success_url(self):
        return reverse_lazy(
            "shop:customer-detail", kwargs={"pk": self.object.pk}
        )


class ManufacturerListView(generic.ListView):
    model = Manufacturer
    context_object_name = "manufacturer_list"
    template_name = "shop/manufacturer_list.html"
    queryset = Manufacturer.objects.all()
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["manufacturer_search_form"] = ManufacturerSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        form = ManufacturerSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return self.queryset


def manufacturer_detail_parts(request, pk):
    manufacturer = Manufacturer.objects.get(pk=pk)
    autoparts_list = manufacturer.autopart_set.all()

    context = {
        "autoparts_list": autoparts_list,
        "manufacturer": manufacturer,
    }

    return render(request, "shop/manufacturer_detail.html", context)


class AutopartListView(generic.ListView):
    model = AutoPart
    context_object_name = "autoparts_list"
    template_name = "shop/autoparts_list.html"
    queryset = AutoPart.objects.all()
    paginate_by = 9

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        part_name = self.request.GET.get("part_name", "")

        context["autoparts_search_form"] = AutopartsSearchForm(initial={
            "part_name": part_name
        })

        return context

    def get_queryset(self):
        form = AutopartsSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                part_name__icontains=form.cleaned_data["part_name"]
            )
        return self.queryset


def add_item_to_order(request, pk):
    if request.user.is_authenticated:
        customer = Customer.objects.get(id=request.user.id)
        part = AutoPart.objects.get(id=pk)

        order, created = Order.objects.get_or_create(owner_id=customer.id)
        order.auto_parts.add(part)
        sweetify.success(
            request,
            "Great",
            text="You successfully add part to order"
        )
    else:
        sweetify.warning(
            request,
            "Sorry",
            text="You must be signed in",
            persistent="Ok"
        )
        return redirect(reverse_lazy("shop:autopart-list"))

    return redirect(reverse_lazy("shop:autopart-list"))


def remove_part_from_order(request, pk):
    owner_id = request.user.id
    part = AutoPart.objects.get(pk=pk)
    order = Order.objects.get(owner_id=owner_id)
    order.auto_parts.remove(part)
    sweetify.success(
        request,
        "Great",
        text="You successfully remove part from order"
    )
    return redirect(reverse_lazy("shop:basket"))


def basket(request):
    if request.user.is_authenticated:
        owner_id = request.user.id
        order, created = Order.objects.get_or_create(owner_id=owner_id)
        summary_cost = sum([part.price for part in order.auto_parts.all()])
        context = {
            "order": order,
            "summary_cost": summary_cost
        }
        return render(request, "shop/basket.html", context=context)
    else:
        sweetify.warning(
            request,
            "Sorry",
            text="You must be signed in",
            persistent="Ok"
        )
        return redirect(reverse_lazy("shop:login"))

templates/shop/autoparts_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="page_title">
    Auto parts List
  </h1>
    <form action="" method="get" class="form-inline">
        {{ autoparts_search_form|crispy }}
        <input type="submit" value="🔍✨" class="btn btn-info" style="margin-left: 7px">
    </form>
  {% if autoparts_list %}
    <table class="table bc_color table-borderless">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Manufacturer</th>
        <th></th>
      </tr>

      {% for autopart in autoparts_list %}
        <tr>
          <td>
              {{ autopart.id }}
          </td>
          <td>
              {{ autopart.part_name }}
          </td>
          <td>
              {{ autopart.price }}$
          </td>
          <td>
              {{ autopart.manufacturer.name }}
          </td>
          <td>
            <a href="{% url 'shop:buy' pk=autopart.id %}" class="btn btn-success link-to-page">
            Buy
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p class="page_title">There are no items in the shop.</p>
  {% endif %}
{% endblock %}

templates/shop/basket.html
{% extends "base.html" %}

{% block content %}
  <h1 class="page_title">
    Your auto parts
  </h1>
  {% if order %}
    <table class="table bc_color table-borderless">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Manufacturer</th>
        <th></th>
      </tr>

      {% for autopart in order.auto_parts.all %}
        <tr>
          <td>
              {{ autopart.id }}
          </td>
          <td>
              {{ autopart.part_name }}
          </td>
          <td>
              {{ autopart.price }}$
          </td>
          <td>
              {{ autopart.manufacturer.name }}
          </td>
          <td>
              <a class="btn btn-danger" href="{% url 'shop:remove' pk=autopart.id %}">Remove</a>
          </td>
        </tr>
      {% endfor %}
    </table>
      <br>
    <h4 class="page_title"> Summary cost your parts: {{ summary_cost }}$</h4>

  {% else %}
      <p>There are no items in the basket.</p>
  {% endif %}
{% endblock %}

templates/shop/customer_detail.html
{% extends "base.html" %}

{% block content %}
  <h1 class="page_title">
    Username: {{ customer.username }}
    <a href="{% url 'shop:customer-update' pk=customer.id %}" class="btn btn-secondary link-to-page">
      Update your profile
    </a>
    {% if user.is_staff %}
    <a href="/admin/" class="btn btn-secondary link-to-page">
      Go to admin page
    </a>
    {% endif %}
  </h1>
  <div class="bc_color customer_detail">
    <p><strong>First name:</strong> {{ customer.first_name }}</p>
    <p><strong>Last name:</strong> {{ customer.last_name }}</p>
    <p><strong>Email:</strong> {{ customer.email }}</p>
    <p><strong>Is staff:</strong> {{ customer.is_staff }}</p>
  </div>

{% endblock %}

templates/shop/customer_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="page_title">Update your profile</h1>
  <form class="bc_color" action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a class="btn btn-secondary" href="{% url 'shop:customer-detail' pk=customer.id %}">Back</a>
  </form>
{% endblock %}

templates/shop/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="home">
        <h1>Auto-parts Shop Home</h1>
        <hr>
        <h3 style="margin-top: 5px">
            We better than other web-store because:
        </h3>
        <div class="count_img">
            <img src="{% static 'images/manufacturer.jpg' %}" alt="manufacturer">
            <div class="info">We work with {{ manufacturer_count }} manufacturers</div>
        </div>
        <div class="count_img">
            <img src="{% static 'images/autoparts.png' %}" alt="autoparts">
            <div class="info">We already have {{ autoparts_count }}pcs auto-parts</div>
        </div>
        <div class="count_img customers">
            <img src="{% static 'images/customers.png' %}" alt="customers">
            <div class="info">We have {{ users_count }} users registered</div>
        </div>
    </div>
{% endblock %}

templates/shop/manufacturer_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="page_title">
    Auto parts List for manufacturer: {{ manufacturer.name }}({{ manufacturer.country }})
  </h1>

  {% if autoparts_list %}
    <table class="table bc_color table-borderless">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th></th>
      </tr>

      {% for autopart in autoparts_list %}
        <tr>
          <td>
              {{ autopart.id }}
          </td>
          <td>
              {{ autopart.part_name }}
          </td>
          <td>
              {{ autopart.price }}$
          </td>
          <td>
            <a href="{% url 'shop:buy' pk=autopart.id %}" class="btn btn-success link-to-page">
            Buy
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
      <p class="page_title">There are no items in the shop.</p>
  {% endif %}
    <a class="btn btn-secondary" href="{% url 'shop:manufacturer-list' %}">Back</a>
{% endblock %}

templates/shop/manufacturer_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="page_title">
    Manufacturer List
  </h1>
    <form action="" method="get" class="form-inline">
        {{ manufacturer_search_form|crispy }}
        <input type="submit" value="🔍✨" class="btn btn-info" style="margin-left: 7px">
    </form>
  {% if manufacturer_list %}
    <table class="table bc_color table-borderless">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Country</th>
        <th>Amount parts</th>
      </tr>

      {% for manufacturer in manufacturer_list %}
        <tr>
          <td>
              {{ manufacturer.id }}
          </td>
          <td>
              <a class="link_color" href="{% url 'shop:manufacturer-detail' pk=manufacturer.id%}">{{ manufacturer.name }}</a>
          </td>
          <td>
              {{ manufacturer.country }}
          </td>
          <td>
              {% if manufacturer.autopart_set.count > 0 %}
              {{ manufacturer.autopart_set.count }}
              {% else %}
              Haven`t auto-parts yet...
              {% endif %}
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p class="page_title">There are no manufacturers in the service.</p>
  {% endif %}
{% endblock %}